server:
  port: 80

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/


ribbon:
  ReadTimeout: 5000
  ConnectionTimeout: 5000
feign:
  hystrix:
    enabled: true

logging:
  level:
    com.starry.springcloud.service: debug
    com.starry.springcloud.controller: debug
